name: Deploy Laravel App

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install Composer dependencies
      run: composer install --no-dev --prefer-dist --no-progress

    - name: Configure environment
      run: php artisan config:cache

    - name: Deploy Laravel App (Dry Run)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        server-dir: ${{ secrets.FTP_DESTINATION_LARAVELAPP }}
        local-dir: ./
        exclude: |
          node_modules/**         # Excluye node_modules y su contenido
          .git/**                 # Excluye .git y su contenido
          .github/**              # Excluye .github y su contenido
          .env                    # Excluye el archivo .env
          storage/framework/cache/** # Excluye el contenido de cache
          storage/framework/testing/** # Excluye el contenido de testing
          tests/**                # Excluye la carpeta tests y su contenido
          *.log                   # Excluye archivos con extensión .log
          vite.config.js          # Excluye vite.config.js
          tailwind.config.js      # Excluye tailwind.config.js
        dry-run: true

    - name: Deploy Laravel App
      if: always() # Solo despliega si el dry-run no reportó errores
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        server-dir: ${{ secrets.FTP_DESTINATION_LARAVELAPP }}
        local-dir: ./
        exclude: |
          node_modules/**         # Excluye node_modules y su contenido
          public/**               # Excluye la carpeta public y su contenido
          .git/**                 # Excluye .git y su contenido
          .github/**              # Excluye .github y su contenido
          .env                    # Excluye el archivo .env
          storage/framework/cache/** # Excluye el contenido de cache
          storage/framework/testing/** # Excluye el contenido de testing
          tests/**                # Excluye la carpeta tests y su contenido
          *.log                   # Excluye archivos con extensión .log
          vite.config.js          # Excluye vite.config.js
          tailwind.config.js      # Excluye tailwind.config.js

    - name: Deploy Public Folder
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        server-dir: ${{ secrets.FTP_DESTINATION_LARAVELPUBLIC }}
        local-dir: ./public/
        exclude: |
          fotosviejo/**           # Excluye la carpeta fotosviejo y su contenido

    - name: Configure Permissions
      run: |
        chmod -R 775 storage
        chmod -R 775 bootstrap/cache
