name: Deploy Laravel App

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Cache NPM dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    # 6. Compilar assets si es necesario
    - name: Compilar assets con NPM
      run: |
        npm install
        npm run build
      if: steps.cache.outputs.cache-hit != 'true'

    # 7. Preparar configuración de Laravel
    - name: Configurar entorno
      run: php artisan config:cache

    # 8. Subir el contenido del proyecto Laravel (excepto la carpeta `public`)
    - name: Deploy Laravel App
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        server-dir: ${{ secrets.FTP_DESTINATION_LARAVELAPP }}
        exclude: |
          public/
          node_modules/
          vendor/
          .env
          .git/
          '**/lost+found/**'
        local-dir: ./

    # 9. Subir el contenido de la carpeta `public` a `public_html`
    - name: Deploy Public Folder
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        server-dir: ${{ secrets.FTP_DESTINATION_LARAVELPUBLIC }}
        local-dir: ./public/
        exclude: |
          .env
          storage/logs/
          node_modules/
          '**/lost+found/**'

    # 10. Ajustar permisos para carpetas de Laravel
    - name: Configurar permisos
      run: |
        chmod -R 775 storage
        chmod -R 775 bootstrap/cache