name: Deploy Laravel App

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install NPM dependencies
        run: |
          if ! command -v npm &> /dev/null; then
            npm install
          fi

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: |
          if ! command -v composer &> /dev/null; then
            composer install --no-dev --prefer-dist --no-progress
          fi

      - name: Compile assets with NPM
        run: npm run build

      - name: Configure environment
        run: php artisan config:cache

      - name: Deploy Laravel App
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          server-dir: ${{ secrets.FTP_DESTINATION }}
          exclude: |
            **/vendor/**
            **/tests/**
            **/node_modules/**
            **/.git*
            **/.git*/**
            .env
            .env.example
            .gitignore
            .gitattributes

      - name: Install lftp
        run: |
          if ! command -v lftp &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y lftp
          fi

      - name: Move public files to public_html
        run: |
          lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "mirror -R public/ public_html/; quit"