name: Deploy Laravel App

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install NPM dependencies
      run: npm install

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --no-dev --prefer-dist --no-progress

    - name: Compilar assets con NPM
      run: npm run build

    - name: Configurar entorno
      run: php artisan config:cache

    - name: Deploy Laravel App
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        server-dir: ${{ secrets.FTP_DESTINATION_LARAVELAPP }}
        exclude: |
          public/
          node_modules/
          vendor/
          .env
          .git/
          '**/lost+found/**'
        local-dir: ./

    - name: Deploy Public Folder
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        server-dir: ${{ secrets.FTP_DESTINATION_LARAVELPUBLIC }}
        local-dir: ./public/
        exclude: |
          .env
          storage/logs/
          node_modules/
          '**/lost+found/**'

    - name: Configurar permisos
      run: |
        chmod -R 775 storage
        chmod -R 775 bootstrap/cache